apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-addresspool-sample1
  namespace: metallb-system
spec:
  addresses:
    - 192.168.127.100-192.168.127.110
  autoAssign: true
  avoidBuggyIPs: true
